# Generated by Django 4.2.29 on 2026-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('path', models.URLField(max_length=255, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
