# Generated by Django 4.2.29 on 2026-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
