# Generated by Django 4.2.29 on 2026-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodul', '0002_alter_person_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
