# Generated by Django 4.2.29 on 2026-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodul', '0004_alter_person_options_alter_person_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
