# Generated by Django 4.2.29 on 2026-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodul', '0006_alter_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
