# Generated by Django 4.2.29 on 2026-06-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminmodul', '0007_alter_person_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('userpath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
