# Generated by Django 4.2.29 on 2026-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
