# Generated by Django 4.2.29 on 2026-05-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesstorage', '0002_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
    ]
