# Generated by Django 4.2.29 on 2026-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesstorage', '0003_remove_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
