# Generated by Django 4.2.29 on 2026-05-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesstorage', '0004_alter_file_last_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
