# Generated by Django 4.2.29 on 2026-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesstorage', '0006_remove_file_last_downloaded_filedownloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FileDownloadHistory',
        ),
    ]
